# government misconduct-tracker

Créer un site web avec toutes les "crasses" du gvt par catégorie/domaine politique ? (Envt, société,etc..) Que ce soit les affaires médiatisées comme contrôle abusif, etc.. + ajouter les promesses non tenues etc.. MAIS TOUT SOURCÉ ET LORSQUE AVÉRÉ
--> compilation et bien garder en mémoire le tout

S'amuser a faire une prédiction (quand est ce que la prochaine dingz arrive ??)

# clmimbing

GenAI / reproduction ultra fidèle/facilitée des prises d'escalades en mode indoor (cf mimic holds) --> amener un big gap techno?
--> créer une base de données de prises d'escalade avec des scans 3D hyper précis
--> créer un algo de reproduction de prises d'escalade en 3D hyper fidèle
--> créer une interface utilisateur pour permettre aux grimpeurs de concevoir leurs propres murs d'escalade avec des prises personnalisées
--> possibilité d'intégrer des fonctionnalités de réalité augmentée pour visualiser les prises sur un mur
--> possibilité d'intégrer des fonctionnalités de réalité virtuelle pour simuler l'escalade avec les nouvelles prises
--> possibilité de créer une marketplace pour vendre les prises d'escalade personnalisées

# cultural recommendations website/app

Nouvelle feature ou blog perso sur recommandations tah les videos ytb de tournesol mais pour des articles, blogpost, documentaire, article scientifique ou tout documents revues par toute la communauté sur des avis et comparaison par paires (cf tournesol)

nom : friendR --> R with friend for everything but R
onglet : partage de contenus --> recommandation entre amis de contenus : nom du contenu (livre, manga,serie,nimporte),
url, wikipedia, autre si besoin avec système de ranking selon apparition/croisement d autres source
(+ pour fun mais biaisé ajouter des poids/coeffs selon ressemblance entre les gens
(cf projection factorielle des qu on a des datas entre les gens) et laisser le choix si tu veux des contenus
objectif basé uniquement sur le ranking apparition etc ou qqch de + personnalisé basé sur tes connexions avec les autres

# skate figure recognition
3e : skate recognition video and movement analytics --> motivation and reason + connection avec
Faire un modele DP de reco de figure de skate (video ducoup)
avec en temps reel lecture des figures etc..
(ensuite peux s appliquer a n'importe quel truc sportif genre gym, danse etc.. pour reconnaitre des figures connues, utiliser GAN + contraintes musculaires humaines pour explorer d autres figures?)
-aller chercher donnes étiquetés video ytb (batb,etc..)

bien normaliser les videos (faire une suite de frame et prendre par ex 5 ou 10 frames pour toutes les figures et donc mettre en entrée du réseau des matrices "empilees" avec 3*Nbr de frames comme dimension (1 matrice par figure étiquetée)
ou bien essayer de voir comment faire du traitement videi

-essayer des GAN controlable pour 'inventer' de nouvelles figures possibles pour l homme

alternative : un peu comme taff de langue des signes et taffer avec mediapipe sur reco des mouvements !

# idee blog posts

2e : organizeR histoire, motivations et comment ça a été fait,
4e article : comment comprendre et avoir confiance dans le score de l'algo? --> article sur interprétabilité avec ce use-case.

# resource fetcher & adder

Resource fetcher/adder - type : je prend des notes sur keep (avec keep API) ou autres et hop ça va ajouter mon petit texte dans un fichier direct sur le git

# recipeR adder ?
- Ajout auto dans database recette --> direct dans l'app recipeR
potential data to scrap : https://www.lemonde.fr/les-decodeurs/article/2025/12/07/140-idees-de-recettes-vegetariennes-pour-les-fetes-de-fin-d-annee_6656360_4355770.html

# eye tracking project

Idée pour améliorer projet ingé :

utiliser GAN pour interpréter les apprentissages des neurones a l échelle individuelle
-bayesian optimsiation

utilisation de l espace latent des GANs (controllable gans) pour forcer un trait de caractéristiques (sourire par ex ou quoi pour un truc de visages)

# one piece character recognition and analysis
Idees app :
- One piece nice charcater database (+ compter nbr de pages où ils apparaissent??
Gagnetondebat -> fournit des infos sources des différents débats de société, organisés en catégories etc.. avec qqs graphs clés pour digérer l'info et qui pointe vers les sources + compléments infos + paragraphes rédigés avec les arguments
idee : chat with a manga --> make RAG with manga (e.g. one piece)

extract all text from :
https://github.com/adhikary97/One-Piece-Database?tab=readme-ov-file

# sport tracking data app
oriented for fitness workout tracking and analysis

## for R with quarto-live

data manipulation, visualization with ggplot2, dplyr, etc..
in-depth tutorials on specific topics
statistical modeling with lm(), glm(), etc..

## for python with pyodide

easy data manipulation with polars, plotnine, etc..
in-depth tutorials on specific topics
statistical modeling with statsmodels, scikit-learn, etc..
machine learning with scikit-learn, tensorflow, etc..

# analyse teamfighttactics data (personal and global?)

# analyse boardgames data

## catan
to see which strategies work best

## 7 wonders
analyze card drafting strategies

## evolution
analyze trait combinations and their effectiveness

## harmonies ?
